FROM amazon/aws-glue-libs:glue_libs_4.0.0_image_01


#RUN mamba install --yes 'delta-spark' && \
#    mamba clean --all -f -y && \
#    fix-permissions "${CONDA_DIR}" && \
#    fix-permissions "/home/${NB_USER}"


# RUN apt-get update && sudo apt-get install awscli --yes && aws --version
#RUN pip3 install --upgrade pip
#RUN pip3 install delta-spark

#RUN echo 'spark.sql.extensions io.delta.sql.DeltaSparkSessionExtension' >> "${SPARK_HOME}/conf/spark-defaults.conf" && \
#    echo 'spark.sql.catalog.spark_catalog org.apache.spark.sql.delta.catalog.DeltaCatalog' >> "${SPARK_HOME}/conf/spark-defaults.conf"


# Trigger download of delta lake files
#RUN echo "from pyspark.sql import SparkSession" > /tmp/init-delta.py && \
#    echo "from delta import *" >> /tmp/init-delta.py && \
#    echo "spark = configure_spark_with_delta_pip(SparkSession.builder).getOrCreate()" >> /tmp/init-delta.py && \
#    python /tmp/init-delta.py && \
#    rm /tmp/init-delta.py