FROM python

WORKDIR /app

COPY . .

USER root
RUN pip install --no-cache --trusted-host pypi.org --trusted-host files.pythonhosted.org --upgrade pip
#RUN pip install --no-cache --trusted-host pypi.org --trusted-host files.pythonhosted.org -r 'requirements.txt'
RUN pip install --no-cache --trusted-host pypi.org --trusted-host files.pythonhosted.org -r 'requirements.txt' -t ./lib

EXPOSE 8888